[package]
name = "esus"
version = "0.1.0"
authors = ["Azorlogh <bott.alix@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
log = "0.4"
simple_logger = { version = "1.6.0", default-features = false }
winit = "0.22.2"
wgpu = "0.5.2"
futures = "0.3.0"
shaderc = "0.6.2"
zerocopy = "0.3.0"
kurbo = "0.6.2"
wgpu_glyph = "0.9.0"
ab_glyph = "0.2.5"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.6"
